[versions]
ktor = "3.2.1"

[libraries]
ktor-server-cio = { group="io.ktor", name="ktor-server-cio", version.ref="ktor" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version = "2.1.20" }
