name: Cache test
on:
  workflow_dispatch:


jobs:
  cache-test:
    runs-on: ubuntu-latest
    steps:

      - name: Cache current date
        uses: actions/cache/restore@v4
        id: cache-now-restore
        with:
          path: |
            ~/now.txt
          key: ${{ runner.os }}-now

      - name: Check cache hit
        run: |
          echo "Cache hit: ${{ steps.cache-now-restore.outputs.cache-hit}}."

      - name: Get restored value
        run: if [ -f ~/now.txt ]; then cat ~/now.txt; fi

      - name: Calculating now date
        run: date '+%Y-%m-%d %H:%M:%S' > ~/now.txt

      - name: Get new value
        run: cat ~/now.txt

      - name: Cache now.txt
        id: cache-now-store
        uses: actions/cache/save@v4
        with:
          path: |
            ~/now.txt
          key: ${{ steps.cache-now-restore.outputs.cache-primary-key }}
